services:
  - type: web
    name: sicmi-sarl
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sicmi_site.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
